# Generated by Django 3.1.4 on 2021-02-15 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_auto_20210105_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('blacklisted', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='data.entity')),
            ],
            options={
                'unique_together': {('entity', 'type')},
            },
        ),
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=3)),
                ('method', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='digest',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='data.blob'),
        ),
        migrations.CreateModel(
            name='EntityHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_source', models.CharField(max_length=256)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.digest')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.entity')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='data.languagemodel')),
            ],
        ),
    ]
