# Generated by Django 3.1.4 on 2021-02-15 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_auto_20210215_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='languagemodel',
            old_name='method',
            new_name='engine',
        ),
        migrations.AddField(
            model_name='languagemodel',
            name='description',
            field=models.CharField(default=' ', max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.entitytype'),
        ),
    ]
