# Generated by Django 3.1.4 on 2021-02-15 10:46

from django.db import migrations

entity_type_list = ['ORG', 'PER', 'LOC', 'CARDINAL', 'DATE', 'EVENT', 'FAC', 'GPE',
                    'LANGUAGE', 'MONEY', 'NORP', 'ORDINAL', 'PERCENT', 'PERSON', 'PRODUCT', 'QUANTITY',
                    'TIME', 'WORK_OF_ART']


def create_entity_types(apps, schema_editor):
    Type_model = apps.get_model('data', 'EntityType')
    for entity in entity_type_list:
        type_entry = Type_model(type=entity)
        type_entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_auto_20210215_1045'),
    ]

    operations = [
        migrations.RunPython(create_entity_types),
    ]
