# Generated by Django 3.1.4 on 2021-04-29 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_auto_20210215_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityhit',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.languagemodel'),
        ),
    ]
